# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo
  
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ '{{' }} checksum "Pipfile.lock" {{ '}}' }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: v1-dependencies-{{ '{{' }} checksum "Pipfile.lock" {{ '}}' }}
          paths:
            - ~/.local
            - ~/.cache

      - run:
          name: generate project
          command: |
            git clone git@github.com:fangpenlin/rocket-launcher-sampleapp.git
            pipenv run cookiecutter -f --no-input . -o rocket-launcher-sampleapp
