# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/repo
  
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: Install dependencies
          command: pipenv sync --dev

      - run:
          name: Generate project
          command: pipenv run cookiecutter -f --no-input . -o output

      - save_cache:
          key: v3-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

  deploy:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:f0:23:6c:e8:4c:f5:bf:7a:83:a7:9b:53:b2:2e:83"

      - run:
          name: Push to sampleapp repo
          command: |
            git config --global user.email "hello@fangpenlin.com"
            git config --global user.name "Fang-Pen Lin"
            eval `ssh-agent`
            ssh-agent $(ssh-add ~/.ssh/id_rsa_e3f0236ce84cf5bf7a83a79b53b22e83; git clone --no-checkout git@github.com:fangpenlin/rocket-launcher-sampleapp.git)
            cp -r rocket-launcher-sampleapp/.git output/sampleapp
            cd output/sampleapp
            git add --all
            git commit --allow-empty -m "Generated from rocket-launcher $CIRCLE_SHA1"
            ssh-agent $(ssh-add ~/.ssh/id_rsa_e3f0236ce84cf5bf7a83a79b53b22e83; git push origin master)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
